"""add duty teams and user birthday

Revision ID: 43f79b577311
Revises: 68815e7c3812
Create Date: 2026-09-01 00:47:14.695057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '43f79b577311'
down_revision: Union[str, None] = '68815e7c3812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duty_team',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('rotation_interval_days', sa.Integer(), nullable=False),
    sa.Column('created_by_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty_team_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['duty_team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'order_index', name='uq_duty_team_member_order'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_duty_team_member_user')
    )
    op.create_index(op.f('ix_duty_team_member_team_id'), 'duty_team_member', ['team_id'], unique=False)
    op.add_column('duty', sa.Column('team_id', sa.Uuid(), nullable=True))
    op.alter_column('duty', 'rotation_interval_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_duty_team_id'), 'duty', ['team_id'], unique=False)
    op.create_foreign_key(None, 'duty', 'duty_team', ['team_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birthday')
    op.drop_constraint(None, 'duty', type_='foreignkey')
    op.drop_index(op.f('ix_duty_team_id'), table_name='duty')
    op.alter_column('duty', 'rotation_interval_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('duty', 'team_id')
    op.drop_index(op.f('ix_duty_team_member_team_id'), table_name='duty_team_member')
    op.drop_table('duty_team_member')
    op.drop_table('duty_team')
    # ### end Alembic commands ###
